plugins {
    id 'java'
    id 'net.minecraftforge.gradle' version '[6.0,6.2)'
}

group = 'com.gleb'
version = '1.0.0'

java {
    toolchain.languageVersion = JavaLanguageVersion.of(17)
}

minecraft {
    mappings channel: 'official', version: '1.21.1'
}

repositories {
    maven { url = 'https://maven.minecraftforge.net/' }
    mavenCentral()
}

dependencies {
    minecraft 'net.minecraftforge:forge:1.21.1-52.0.1'
}

jar {
    manifest {
        attributes([
            'Specification-Title': 'glebclient',
            'Specification-Version': '1.0.0',
            'Implementation-Title': 'Gleb Client',
            'Implementation-Version': '1.0.0'
        ])
    }
}
